/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/close-expired/wrangler.jsonc --include-runtime=false workers/close-expired/worker-configuration.d.ts` (hash: 8df3bdba1eb03aa1c7f9dcf9a51edce1)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
